# Generated by Django 4.1.7 on 2023-04-04 07:21

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('image', models.ImageField(default='player_images/default_player_image.jpg', upload_to='player_images')),
                ('jersey_no', models.PositiveSmallIntegerField()),
                ('format', models.CharField(choices=[('T20', 'T20'), ('ODI', 'ODI'), ('Test', 'Test'), ('All Formats', 'All Formats')], max_length=11)),
                ('type', models.CharField(choices=[('Batter', 'Batter'), ('Bowler', 'Bowler'), ('WicketKeeper Batter', 'WicketKeeper Batter'), ('All Rounder', 'All Rounder')], max_length=19)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('logo', models.ImageField(default='team_logo/team_logo.jpg', upload_to='team_logo')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captain', to='cricket_app.player')),
                ('players', models.ManyToManyField(related_name='all_players', to='cricket_app.player')),
                ('playing_eleven', models.ManyToManyField(related_name='playing_eleven', to='cricket_app.player', verbose_name='Playing XI')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_squad', to='cricket_app.team')),
                ('vice_captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vice_captain', to='cricket_app.player')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_team', to='cricket_app.team'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Live', 'Live'), ('Finished', 'Finished')], max_length=10)),
                ('result', models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Draw', 'Draw'), ('Abandoned', 'Abandoned')], max_length=10, null=True)),
                ('type', models.CharField(choices=[('T20', 'T20'), ('ODI', 'ODI'), ('Test', 'Test')], max_length=10)),
                ('result_description', models.CharField(blank=True, max_length=100, null=True)),
                ('squad_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad_one', to='cricket_app.squad')),
                ('squad_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad_two', to='cricket_app.squad')),
                ('team_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_one', to='cricket_app.team')),
                ('team_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_two', to='cricket_app.team')),
                ('toss', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toss', to='cricket_app.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='cricket_app.team')),
            ],
            options={
                'verbose_name_plural': 'Matches',
                'ordering': ['id'],
            },
        ),
    ]
